apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: q80pjq393-python-gitops
  description: This is GitOps manifest for q80pjq393-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=q80pjq393-python
    backstage.io/kubernetes-id: q80pjq393-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: q80pjq393-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:q80pjq393-python
