apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q80pjq393-python
  janus-idp.io/tekton: q80pjq393-python
  backstage.io/kubernetes-id: q80pjq393-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: q80pjq393-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
